In [1]:
# import all required libaraies:
import numpy as np
import pandas as pd

In [2]:
# load datsets
data=pd.read_csv('train.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [5]:
# in above dataset having unrelavent features cloumns:
# passengerId, name, ticket,coabin:
# we are going to remove this 4 cloumn from our training data:
data.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [6]:
data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [7]:
sex_column=data['Sex']

In [8]:
sex_column=sex_column.apply(lambda x:1 if x=='male' else 0)

In [9]:
data.drop(['Sex'],axis=1,inplace=True)

In [10]:
data.head()

Survived  Pclass   Age  SibSp  Parch     Fare Embarked
0         0       3  22.0      1      0   7.2500        S
1         1       1  38.0      1      0  71.2833        C
2         1       3  26.0      0      0   7.9250        S
3         1       1  35.0      1      0  53.1000        S
4         0       3  35.0      0      0   8.0500        S

In [11]:
embardked=pd.get_dummies(data['Embarked'],drop_first=True)

In [12]:
data.head()

Survived  Pclass   Age  SibSp  Parch     Fare Embarked
0         0       3  22.0      1      0   7.2500        S
1         1       1  38.0      1      0  71.2833        C
2         1       3  26.0      0      0   7.9250        S
3         1       1  35.0      1      0  53.1000        S
4         0       3  35.0      0      0   8.0500        S

In [13]:
data.drop(['Embarked'],axis=1,inplace=True)

In [14]:
data.head()

Survived  Pclass   Age  SibSp  Parch     Fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [15]:
# now adding the one hote encoded vector in main dataframe
data=pd.concat([data,sex_column,embardked],axis=1)

In [16]:
data.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex  Q  S
0         0       3  22.0      1      0   7.2500    1  0  1
1         1       1  38.0      1      0  71.2833    0  0  0
2         1       3  26.0      0      0   7.9250    0  0  1
3         1       1  35.0      1      0  53.1000    0  0  1
4         0       3  35.0      0      0   8.0500    1  0  1

In [17]:
# now we are going to fill the missing value in age:
np.unique(data['Age'])

array([ 0.42,  0.67,  0.75,  0.83,  0.92,  1.  ,  2.  ,  3.  ,  4.  ,
        5.  ,  6.  ,  7.  ,  8.  ,  9.  , 10.  , 11.  , 12.  , 13.  ,
       14.  , 14.5 , 15.  , 16.  , 17.  , 18.  , 19.  , 20.  , 20.5 ,
       21.  , 22.  , 23.  , 23.5 , 24.  , 24.5 , 25.  , 26.  , 27.  ,
       28.  , 28.5 , 29.  , 30.  , 30.5 , 31.  , 32.  , 32.5 , 33.  ,
       34.  , 34.5 , 35.  , 36.  , 36.5 , 37.  , 38.  , 39.  , 40.  ,
       40.5 , 41.  , 42.  , 43.  , 44.  , 45.  , 45.5 , 46.  , 47.  ,
       48.  , 49.  , 50.  , 51.  , 52.  , 53.  , 54.  , 55.  , 55.5 ,
       56.  , 57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 63.  , 64.  ,
       65.  , 66.  , 70.  , 70.5 , 71.  , 74.  , 80.  ,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,

In [18]:
def input_age(cols):
    Age=cols[0]
    Pclass=cols[1]
    if(pd.isnull(Age)):
        if(Pclass==1):
            return 37
        if(Pclass==2):
            return 29
        else:
            return 24
    else:
        return Age


In [19]:
data['Age']=data[['Age','Pclass']].apply(input_age,axis=1)

In [20]:
np.unique(data['Age'])

array([ 0.42,  0.67,  0.75,  0.83,  0.92,  1.  ,  2.  ,  3.  ,  4.  ,
        5.  ,  6.  ,  7.  ,  8.  ,  9.  , 10.  , 11.  , 12.  , 13.  ,
       14.  , 14.5 , 15.  , 16.  , 17.  , 18.  , 19.  , 20.  , 20.5 ,
       21.  , 22.  , 23.  , 23.5 , 24.  , 24.5 , 25.  , 26.  , 27.  ,
       28.  , 28.5 , 29.  , 30.  , 30.5 , 31.  , 32.  , 32.5 , 33.  ,
       34.  , 34.5 , 35.  , 36.  , 36.5 , 37.  , 38.  , 39.  , 40.  ,
       40.5 , 41.  , 42.  , 43.  , 44.  , 45.  , 45.5 , 46.  , 47.  ,
       48.  , 49.  , 50.  , 51.  , 52.  , 53.  , 54.  , 55.  , 55.5 ,
       56.  , 57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 63.  , 64.  ,
       65.  , 66.  , 70.  , 70.5 , 71.  , 74.  , 80.  ])

In [21]:
# now In pclass column we are going to make it one hot encoded vector:
def one_hot_encoded(col_name):
    unique_val=list(np.unique(col_name))
    encoded=np.zeros((len(col_name),len(unique_val)))
    for i,c in enumerate(col_name):
        encoded[i][unique_val.index(c)]=1
    return encoded
    

In [22]:
pclass=one_hot_encoded(data['Pclass'])

In [23]:
data.drop(['Pclass'],axis=1,inplace=True)

In [24]:
data.head()

Survived   Age  SibSp  Parch     Fare  Sex  Q  S
0         0  22.0      1      0   7.2500    1  0  1
1         1  38.0      1      0  71.2833    0  0  0
2         1  26.0      0      0   7.9250    0  0  1
3         1  35.0      1      0  53.1000    0  0  1
4         0  35.0      0      0   8.0500    1  0  1

In [25]:
pclass=pd.DataFrame(data=pclass)

In [26]:
data=pd.concat([data,pclass],axis=1)

In [27]:
# this is my fianl tarining data:
data.head()

Survived   Age  SibSp  Parch     Fare  Sex  Q  S    0    1    2
0         0  22.0      1      0   7.2500    1  0  1  0.0  0.0  1.0
1         1  38.0      1      0  71.2833    0  0  0  1.0  0.0  0.0
2         1  26.0      0      0   7.9250    0  0  1  0.0  0.0  1.0
3         1  35.0      1      0  53.1000    0  0  1  1.0  0.0  0.0
4         0  35.0      0      0   8.0500    1  0  1  0.0  0.0  1.0

In [28]:
label=data['Survived']

In [29]:
label=pd.DataFrame(data=label)

In [30]:
label.shape

(891, 1)

In [31]:
label=np.array(label)

In [32]:
label

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [33]:
data.drop(['Survived'],axis=1,inplace=True)

In [34]:
data.shape

(891, 10)

In [35]:
# we are going to notrmaized the data:
data=(data-np.mean(data))/np.std(data)

In [36]:
training_data=data

In [37]:
training_data=np.array(data)

In [38]:
training_data.shape

(891, 10)

In [39]:
# class of logistic_regression:

class logistic_regression:
    
    def __init__(self):
        self.w=None
        self.b=None
        
    def linear_d_f(self,x):
        return np.dot(x,self.w.T)+self.b
    
    def sigmoid(self,x):
        return 1.0/(1.0+np.exp(-x))
    
    def loss(self,x,y):
        err=0
        for x,y in zip(X,Y):
            y_pred=self.sigmoid(self.linear_d_f(x))
        return -[(1-y_pred)*np.log(1-y_pred,2) + y_pred*np.log(y_pred,2)] # here 2 is base of log:
    
    def grad_w(self,x,y):
        y_pred=self.sigmoid(self.linear_d_f(x))
        return (y_pred-y)*x
    
    def grad_b(self,x,y):
        y_pred=self.sigmoid(self.linear_d_f(x))
        return (y_pred-y)
    
    def fit(self,X,Y,learning_rate=0.01,epochs=10,initialize=False):
        
        if initialize:
            self.w=np.zeros((1,X.shape[1]))
            self.b=0
            
        for _ in range(epochs):
            dw=0
            db=0
            for x,y in zip(X,Y):
                dw+=self.grad_w(x,y)
                db+=self.grad_b(x,y)
                
            self.w-=learning_rate*dw
            self.b-=learning_rate*db
            
    def predict(self,X):
        Y_pred=[]
        for x in X:
            y_pred=self.sigmoid(self.linear_d_f(x))
            Y_pred.append([1 if i>0.5 else 0 for i in y_pred])
        return np.array(Y_pred)

In [40]:
regression=logistic_regression()

In [90]:
regression.fit(training_data,label,learning_rate=0.005,epochs=990,initialize=True)

In [91]:
Y_pred_traing=regression.predict(training_data)

In [92]:
Y_pred_traing.shape

(891, 1)

In [93]:
label.shape

(891, 1)

In [94]:
correct_count=np.count_nonzero(Y_pred_traing==label)

In [95]:
correct_count

718

In [96]:
accuracy=correct_count/training_data.shape[0]

In [97]:
accuracy*100

80.58361391694724